CRITICAL - 2020-11-12 08:17:52 --> Unable to connect to the database.
#0 C:\xampp7\htdocs\e-klipingnew-master\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp7\htdocs\e-klipingnew-master\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp7\htdocs\e-klipingnew-master\system\Model.php(462): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp7\htdocs\e-klipingnew-master\app\Controllers\User.php(19): CodeIgniter\Model->findAll()
#4 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(918): App\Controllers\User->index()
#5 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp7\htdocs\e-klipingnew-master\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp7\htdocs\e-klipingnew-master\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp7\\htdoc...')
#9 {main}
CRITICAL - 2020-11-12 08:17:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp7\htdocs\e-klipingnew-master\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp7\\htdoc...', 100, Array)
#1 C:\xampp7\htdocs\e-klipingnew-master\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\User), true)
#2 C:\xampp7\htdocs\e-klipingnew-master\system\Debug\Exceptions.php(308): include('C:\\xampp7\\htdoc...')
#3 C:\xampp7\htdocs\e-klipingnew-master\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-12 08:17:56 --> Unable to connect to the database.
#0 C:\xampp7\htdocs\e-klipingnew-master\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp7\htdocs\e-klipingnew-master\system\Database\BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp7\htdocs\e-klipingnew-master\system\Model.php(462): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp7\htdocs\e-klipingnew-master\app\Controllers\User.php(19): CodeIgniter\Model->findAll()
#4 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(918): App\Controllers\User->index()
#5 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 C:\xampp7\htdocs\e-klipingnew-master\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp7\htdocs\e-klipingnew-master\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp7\htdocs\e-klipingnew-master\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp7\\htdoc...')
#9 {main}
CRITICAL - 2020-11-12 08:17:56 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp7\htdocs\e-klipingnew-master\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp7\\htdoc...', 100, Array)
#1 C:\xampp7\htdocs\e-klipingnew-master\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\User), true)
#2 C:\xampp7\htdocs\e-klipingnew-master\system\Debug\Exceptions.php(308): include('C:\\xampp7\\htdoc...')
#3 C:\xampp7\htdocs\e-klipingnew-master\system\Debug\Exceptions.php(174): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
